// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenIdentifier-1]
	_ = x[TokenQuotedIdentifier-2]
	_ = x[TokenNumber-3]
	_ = x[TokenString-4]
	_ = x[TokenPipe-5]
	_ = x[TokenDot-6]
	_ = x[TokenSlash-7]
	_ = x[TokenError - -1]
}

const (
	_TokenKind_name_0 = "TokenError"
	_TokenKind_name_1 = "TokenIdentifierTokenQuotedIdentifierTokenNumberTokenStringTokenPipeTokenDotTokenSlash"
)

var (
	_TokenKind_index_1 = [...]uint8{0, 15, 36, 47, 58, 67, 75, 85}
)

func (i TokenKind) String() string {
	switch {
	case i == -1:
		return _TokenKind_name_0
	case 1 <= i && i <= 7:
		i -= 1
		return _TokenKind_name_1[_TokenKind_index_1[i]:_TokenKind_index_1[i+1]]
	default:
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
